'use strict';
global.window=global;
const assert=require('node:assert/strict');
for(const f of ['object_types','mesh_engine','visualization','game_object_manager','topology_engine','strategic_topology']) require(`./${f}.js`);
function graph(neighbors) {return {vertices:[],cells:Object.entries(neighbors).map(([id,ns],i)=>({id,neighbors:ns,centroid:[i*2,0],vertices:[],attributes:{passable:true}}))};}
const corridor=graph({a:['b'],b:['a','c'],c:['b','d'],d:['c'],island:[]});
const t=TopologyEngine.compute(corridor,{});
assert.equal(t.stats.components,2);assert.equal(t.bridges.length,3);assert(t.cellMetrics.b.articulation);assert(!t.cellMetrics.a.articulation);
assert(t.cellMetrics.b.centrality>t.cellMetrics.a.centrality);assert(t.criticalPoints.some(p=>p.kind==='dead_end'));assert(t.criticalPoints.some(p=>p.kind==='choke'));
const junction=TopologyEngine.compute(graph({center:['a','b','c'],a:['center'],b:['center'],c:['center']}),{});
assert(junction.criticalPoints.some(p=>p.kind==='junction'));
const cycle=TopologyEngine.compute(graph({a:['b','d'],b:['a','c'],c:['b','d'],d:['c','a']}),{});
assert.equal(cycle.bridges.length,0);assert.equal(cycle.stats.articulations,0);
const manager=new GameObjectManager([{id:'objective',position:[2,0],priority:100,influenceRadius:20}]);
assert.throws(()=>manager.addObject({id:'objective'}));
const before=JSON.stringify(t),high=StrategicTopology.compute({topology:t,gameObjects:manager.getObjects()});
manager.updatePriority('objective',20);const low=StrategicTopology.compute({topology:t,gameObjects:manager.getObjects()});
assert(high.values.b>low.values.b);assert.equal(JSON.stringify(t),before);
manager.updateObject('objective',{enabled:false});assert.equal(StrategicTopology.compute({topology:t,gameObjects:manager.getObjects()}).nodes[0].gameObjectInfluence,0);
assert.equal(StrategicTopology.objectInfluenceAtPoint({enabled:true,position:[0,0],priority:100,influenceRadius:10},{position:[10,0]}),0);
assert.equal(new GameObjectManager([{id:'bad',priority:'x',influenceRadius:-2,position:null}]).getObject('bad').priority,50);
assert.deepEqual(new GameObjectManager(JSON.parse(JSON.stringify(manager.getObjects()))).getObjects(),manager.getObjects());
const map=require('./map_draft.json');const signature=MeshEngine.sourceSignature(map);map.gameObjects=manager.getObjects();assert.equal(MeshEngine.sourceSignature(map),signature);
const start=performance.now();const mesh=MeshEngine.generate(map,{spacing:12,maxCells:5000,refinePasses:1});
const ts=performance.now();const actual=TopologyEngine.compute(mesh,map);const elapsed=performance.now()-ts;
assert(actual.nodes.length>0);assert(actual.nodes.every(n=>Number.isFinite(actual.cellMetrics[n.id].chokeScore)));
const source=mesh.cells.find(c=>c.attributes.passable!==false).centroid;
const field=MapVisualizers.getRenderer('distance_field').compute({mesh,source:{x:source[0],y:source[1]}});assert(field.reachable_count>0);
console.log(`PASS: legacy map, distance field, graph fixtures, object persistence, normalization and strategic invalidation. ${mesh.cells.length} cells; topology ${elapsed.toFixed(0)} ms; total ${(performance.now()-start).toFixed(0)} ms.`);
